version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app  # Ensure the working directory is set to /app
    depends_on:
      - moderation_service

  moderation_service:
    build: ./moderation_service
    ports:
      - "8001:8001"
    volumes:
      - ./moderation_service:/app
