services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: chat_moderation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net
  
  moderation_service:
    build: ./moderation_service
    volumes:
      - ./moderation_service:/app
    env_file:
      - ./.env
    networks:
      - backend_net
  
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    # volumes:
    #   - ./backend:/app
    env_file:
      - ./.env
    # environment:
    #   PYTHONPATH: "/app/backend"  # Ensure the PYTHONPATH is set correctly
    #   DJANGO_SETTINGS_MODULE: "backend.settings"  # Explicitly set the settings module
    networks:
      - backend_net
    depends_on:
      - moderation_service
      - db

volumes:
  postgres_data:

networks:
  backend_net:
