# Generated by Django 5.2 on 2025-04-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='moderation_labels',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
