# Generated by Django 5.2 on 2025-04-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_comment_moderation_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='moderation_labels',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
